[package]
name = "libmatcompl"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
rand = "0.9.2"

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }

[[bench]]
name = "benches"
harness = false
